builds:
- env:
  - CGO_ENABLED=0
  binary: security-monitor-scanners
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: deepnetworkgmbh
    name: homebrew-tap
  folder: Formula
  description: Scanners/Auditors for Security Monitor
  test: |
    system "#{bin}/security-monitor-scanners --version"
