apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanners-passing-deployment
  labels:
    app: scanners-passing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanners-passing-deployment
  template:
    metadata:
      labels:
        app: scanners-passing-deployment
    spec:
      containers:
        - command:
            - scanners
          image: 'deepnetwork/scanners:0.1.0'
          imagePullPolicy: 'Always'
          name: scanners
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
